# -*- coding: utf-8 -*-
"""append_time_to_log.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cEpH2zZTkf6bmdUzxdE7_UJ-LjN6iMdi
"""

import datetime

def append_current_time_to_file(file_path):
    # 現在の時刻を取得
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ファイルを開いて追記モードで書き込み
    with open(file_path, 'a') as file:
        file.write(current_time + '\n')

# ファイルへのパスを指定
file_path = './time_log.txt'
# プログラムを実行して現在の時刻をファイルに追記
append_current_time_to_file(file_path)